keys:
  - &admin_kaki B0F6B192E4253A5DBD33A7F2D2A9353AEDF9200A
  - &admin_yusuke age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_kaki
        age:
          - *admin_yusuke
  - path_regex: infra/*
    key_groups:
      - pgp:
          - *admin_kaki
        age:
          - *admin_yusuke
  - path_regex: systems/nixos/services/dropbox/secrets.yaml$
    key_groups:
      - pgp:
          - *admin_kaki
        age:
          - *admin_yusuke
  - path_regex: systems/nixos/rem/secrets.yaml$
    key_groups:
      - pgp:
          - *admin_kaki
        age:
          - *admin_yusuke
