keys:
  - &admin_kaki B0F6B192E4253A5DBD33A7F2D2A9353AEDF9200A
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_kaki 
  - path_regex: infra/*
    key_groups:
      - pgp:
          - *admin_kaki 
