version: '3'
vars:
  HOST:
    sh: uname -n
  NIX_PROFILE: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  NIX: '{{.NIX | default "nom"}}'
tasks:
  build:
    desc: 現在のシステム向けのNix Configurationをビルドします
    deps:
      - task: '{{OS}}'
  build-all:
    desc: 全てのシステムのNix Configurationをビルドします
    deps:
      - linux
      - darwin
  linux:
    desc: 全てのLinux (x86_64) ホスト向けのビルド
    cmds:
      - |
        {{.NIX}} build --impure --keep-going --no-link --show-trace --system x86_64-linux \
          .#nixosConfigurations.lawliet.config.system.build.toplevel \
          .#nixosConfigurations.ryuk.config.system.build.toplevel \
          .#nixosConfigurations.rem.config.system.build.toplevel
  darwin:
    desc: macOS (aarch64) 向けのビルド
    cmds:
      - "{{.NIX}} build --keep-going --no-link --show-trace --system aarch64-darwin --option extra-sandbox-paths /nix/store \\\n  .#darwinConfigurations.watari.system\n  \n"
  install_nix:
    desc: Determinate Systemsのインストーラを使ってNixをインストールします
    status:
      - test -f {{.NIX_PROFILE}}
  uninstall_nix:
    cmds:
      - /nix/nix-installer uninstall
