#ENC[AES256_GCM,data:NCq2Rgtt2e52+nHhgrpurudxl4uRJFpDbRIfVy0=,iv:tUaRijFtOQc/qOObx/e2iI8+Ips10dLD1XabNfB2uXM=,tag:2QiBWkX1q2yIl8FfHP2gKA==,type:comment]
terraform:
  backend:
    #ENC[AES256_GCM,data:YJIlbdEpPFy+w092/ht9/1A+2G10c1Nu+/feeU8SQQWf7ljh8eWZCCdOdA==,iv:wa7+BkXrusvnFO7KyA0tDPjleMK2pfDgpi38BkYhveg=,tag:FRs89dd6SW54ppEMQgR2tA==,type:comment]
    oci:
      bucket: ENC[AES256_GCM,data:aJVVvTqgJPGU5668EtbWZg==,iv:COKZlid2aM76eAaxvGRwGakBt77VzqL7C4uiTcqd8s8=,tag:O1Sju9lL/V3KPp1yqfniWg==,type:str]
      namespace: ENC[AES256_GCM,data:Vt2kCkkYo259eipi,iv:15FVPYFdhfyP5JnGVByc3dtqxhK7USWnnrQblcDM01w=,tag:aoAGS6cMcUIR6X3NiLp3cQ==,type:str]
      region: ENC[AES256_GCM,data:isdOiw8sHMlJWg==,iv:6a2Abeh1z+PtCrQv2w6xYFILde6ivvtpYSN5d7XoxmM=,tag:/3uerNVFG+46kRwt5ymCSA==,type:str]
      tenancy_ocid: ENC[AES256_GCM,data:mrhLlyGhii+F+xDaUl8Z86Mgx5h3VQTcA1FCwtczDVMS6pVuT/ktgqzpAt1VJPOmYB0hCyLm47F6seXgFGakG1+dEt9JPt0Hv1IT0DsI0Q==,iv:N0zdqkfPZqw8UTG0Vw9qJqLCZ4kQl7GetRVvvN3qpJw=,tag:K9MmP1grTaMALgUAvVjweQ==,type:str]
      user_ocid: ENC[AES256_GCM,data:WQx7NZwrROYLMoHg86NUpFWPxVatK1ptDPjSf1oQzJ4tVPb3QkeXLUJsZX2trKc9LLc9Oc1bbsF2YLK2iBgIhLWtub/9MIad90gBlQ==,iv:hsP1AyNEIVpzxhNj8Sm7+Je6N9CbKZBRdtO5Bcs5vsQ=,tag:i5m22uvS4EzfVGt+5Ut95w==,type:str]
      fingerprint: ENC[AES256_GCM,data:JFEe13muqYmD8kT+v8E7F/+krm4n+GP97WBb6/m8pi4HzsKrfqyNhrkxjg6d5+o=,iv:fnSHrwEhe4L9fz86u2Ys3JOxI57/o1SspLXUJ4AShKM=,tag:FDAJ6pxFeccxZze1JfDhhg==,type:str]
      private_key_path: ENC[AES256_GCM,data:7q6uzzNY+gVipNCbaARWVQj17k5SPi4z9CtvvmTPo/xaefp6Fc7FIe9HyEVj/tjxWV7EPUa03eh6y+u051sS,iv:7iVSw8ecoNztX00EJBO8CI7YfEag93D1A7hJoCCqrG8=,tag:zt0dNMes3Hb35yIedQwd+A==,type:str]
    #ENC[AES256_GCM,data:trBUNz/avCJj3bLiUO8ne/2bV6UhGB/E+lsfQr5/Kps0LUjD36LHCZy2oO1mc7TfYvfSjsFu,iv:S/syDs0AL18XZ9zvfCwG8ZJ2PnzZXfQd0ZdTGNKOIPA=,tag:QknowFfO3ruHBgdQnmWUoQ==,type:comment]
    s3_compatible:
      endpoint: ENC[AES256_GCM,data:Rf5aqi0nxj2QB1hfw7Pq4IB3bEO7V7G6QeVTo3vlx4gTypMDqfaX4g1n8kktJo4mDGkUvIwijTdXicPOIKMxdI9MYOw=,iv:SPQaPtHvyPbai1etmHhAUGfvFjwOdvrcbtUvxgazZqU=,tag:jyzJZToZpMs6JX0qpOapRQ==,type:str]
      bucket: ENC[AES256_GCM,data:KZU5GN9dR957d/4twAHGYQ==,iv:BuO27XHVVOMuDXhdl4ShLfIirz8LrAohH/zzYSk2K2U=,tag:DRoG6w0lUzVCFEsm72Rw5g==,type:str]
      region: ENC[AES256_GCM,data:iYxeW1QlWAhueA==,iv:H57OQpkDlOeO1H2NshKLLxyFEOI9UQaXBQ12IcVMdbc=,tag:RaXevJ42sxzBMnlsO6Betg==,type:str]
      access_key: ENC[AES256_GCM,data:BZGk9TSuKUWV5/CmDwT5+1Xhvx5fvI025o+bixvcG0b08e+lWWVyiw==,iv:tpsddpqqrqf3JDkFI2mY8xIewQIbU8wryAxUJGfbFOw=,tag:HD+Ep6MOp5UV5C5X0p/y9g==,type:str]
      secret_key: ENC[AES256_GCM,data:8F7gzuRV/YkIphec2VK097ci1cg/rn82FW+T4UzJfgO3I3/r2xlRpgQVEYY=,iv:2Y9xFUVxS/5uuUnWi1n+ByN1IJQ4Qt7mU/9OMd1E4fs=,tag:knp9nb1CFCAKGMZWSFIIHA==,type:str]
oci:
  root:
    tenancy_ocid: ENC[AES256_GCM,data:/qYPOLOcbNGQrCsfjVwqyP4lKbykFWYlb0PyAQZLXeRmkfn/SwisDMquvmrmVzATD7cdKDzILOiMernn8+ITPdZP9Oe1HCJC56c4dSa7yw==,iv:QaWH3cPRACLVyhGy5PGmyn96JviaFEjJay6VAYJrUpc=,tag:4ndr18xdm8rtVqfISKVw/A==,type:str]
    user_ocid: ENC[AES256_GCM,data:/RSH+FAZlAjkeHCNjKJDtHLFziWsnsBzfZQspTwRljQrWGzDp/DRF9gJ9qwoHnCNcV4NWSJ3fRqF09AugoI1/31sKe1ZtpQD3kQRHA==,iv:Sg+a4rhV9mNPhk1FLWzZKqJWeyrJkRDPoztJ73r92/c=,tag:9UqokrhI6Jxvq2lfMGmt1w==,type:str]
    fingerprint: ENC[AES256_GCM,data:08WnwsPE6avgeoFYm7n4wUoaRmnOBuWZyfIbJCOsGpE5RgcdvpA/sZBfnPKL2nA=,iv:oO4bJK7Ld41QuZMGVp0a5VK2O6QN0e3ZinPwF+xvaTA=,tag:xL2SKwgZMEXbRkmMwMN+1Q==,type:str]
    api_private_key_path: ENC[AES256_GCM,data:G5b0g6UdjlMQ3EFQyRwvAsjdGmRELsX7upQYMZKy2ZXdx+BDecCjbkMS+nLhQBptUI5jyfqYwRjylFwad8GF,iv:hzK2PDjhgfS5M/096EYwC1dLPW8HVSIxnlyI7cJ+6lU=,tag:ns+2Fcg/9tpPCIeX413OTA==,type:str]
  object_storage:
    customer_secret_key:
      access_key: ENC[AES256_GCM,data:iwO5sIInLkM3IXJfvcJ/frv1qGhVMp3aFdCw3l/pM+hHHH2yZJp00g==,iv:gQGtykrplEwrl92UxdeMoX1wxz2tENqgtBKybTmHgTk=,tag:jAtADKaAFN96DSsW2xb4+Q==,type:str]
      secret_key: ENC[AES256_GCM,data:sz+n7S6JUa6CSGv1C9OrFmCogbS9gYHWMH2lpHJEmeEwszzj0Z/x6DLBdmA=,iv:f52gS79HAXgc4f9ZNwguT0rj7oTfXpYm8EFbaPJ2WEw=,tag:0udysuSEsREOThieWvSn0w==,type:str]
sops:
  age:
    - recipient: age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSHpTWURaWU51UzNmS3Y4
        bVYzTldUZVRCMGdaNnRlMno5eGUxcEV2QmdjCnpFYTZzcmc0WjNiRlRyL09YeEJt
        VVNJbGtJaU44bkkxeHprTlN1RTF3VU0KLS0tIHg5RXFoSXRoTHBCS0YySHZJVUow
        N2c4U04yRVJoWU93dzZLWWFIMnlJK3cKGbYeskwM3AWT7SnQxVF6SdsuB26tO19d
        Qklk1WKw2UtAb3wSAtJm55rdy6A0WwfThHLYNdVXVcIl3wEVJ1CKzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-08T16:02:31Z"
  mac: ENC[AES256_GCM,data:lRgDcUEkhjM9cQ+FoTC+uThQAN+I2g/4Uzy11ZfBB34DpGa71dGeI5ysh7uOkmUveSweAItc2ypyCwZCbmN3FGaoWfNK3zxqLRBET49sser5QkIRA5eVgepbz8phQ0mBchNhJ3VMFraKmiWjgJuFhJ82NUzVRY4GWu/onf0ySIE=,iv:04NdeFqAKncTtOQTpYNqzuxmLCfT/2pyOuj4Z6kMpqM=,tag:xzj48av709j1W+zLfDqn+g==,type:str]
  pgp:
    - created_at: "2025-08-08T16:02:31Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hMIDp0xrGzH3GM8SBCMEAGw8FZX7oyez9RMIUo+o8/Z2Lwy/Kk5jB1FnZXjdkFKj
        xjbN4n7rfv7Ii2ddl/IsWVif/1dqtI6D3qL7c97qu8LxAHvIKOsP+C5zOOYkrojq
        CZuUMug2C0jCXHZG8TCXy8a37z8AB/UG51XnLVcyRAx8jSArccfgnMfR0ftdBYvc
        6RscMPGvoG9WyuSo6PqJhkAtNwwOI/EF/Z5NG6Gdc3OvIo8IXdxk6dhLJpJVemBV
        DU2/r9JeAWC2wwSancK1yYroscKl1X9Y3resArh5uLX2UhrbtGXeMt6Wswko1ma+
        2YmN0VrbVxICwZuZyxcvyOnaRLNDb/MvBdy6wafdUsMQfNXei4Ylv1y7yKiwkzF+
        0iU90g==
        =XZAq
        -----END PGP MESSAGE-----
      fp: B0F6B192E4253A5DBD33A7F2D2A9353AEDF9200A
  unencrypted_suffix: _unencrypted
  version: 3.10.2
