return {
	{
		name = "barbar.nvim",
		dir = "@barbar_nvim@",
	},
	{
		name = "vim-markdown",
		dir = "@vim_markdown@",
		config = function()
			vim.g.vim_markdown_folding_disabled = 1
		end
	},
	{
		'navarasu/onedark.nvim',
		opts = {
			style = 'dark',
		},
	},
	{
		name = "vimtex",
		dir = "@vimtex@",
		config = function()
			vim.g.vimtex_view_method = "skim"
		end,
		ft = { "tex" },
	},
	{
		"vim-skk/skkeleton",
		dependencies = {
			name = "denops.vim",
			--dir = "/nix/store/zn4vp6lga0kr7r6nnpl66768i9ajm9wg-vimplugin-denops.vim-2024-04-17",
			dir = "@denops_vim@",
			--"vim-denops/denops.vim",
			config = function()
				-- vim.g['denops#deno'] = '/nix/store/l3adf02p4xdxlvqy5rl2wzb37965nvml-deno-1.43.6/bin/deno'
				vim.g['denops#deno'] = 'deno'
			end
		},
		config = function()
			vim.cmd([[
			call skkeleton#config({ 'globalDictionaries': ['~/.skk/SKK-JISYO.L'] })
			call skkeleton#register_kanatable('rom', {
				\ "\\": "katakana",
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "ca": ["か"],
				\ "ci": ["き"],
				\ "cu": ["く"],
				\ "ce": ["け"],
				\ "co": ["こ"],
			\ })
			call skkeleton#register_kanatable('rom', {
				\ "cga": ["きゃ"],
				\ "cgi": ["きぃ"],
				\ "cgu": ["きゅ"],
				\ "cge": ["きぇ"],
				\ "cgo": ["きょ"],
				\ "sha": ["しゃ"],
				\ "shi": ["しぃ"],
				\ "shu": ["しゅ"],
				\ "she": ["しぇ"],
				\ "sho": ["しょ"],
				\ "tha": ["ちゃ"],
				\ "thi": ["ちぃ"],
				\ "thu": ["ちゅ"],
				\ "the": ["ちぇ"],
				\ "tho": ["ちょ"],
				\ "nha": ["にゃ"],
				\ "nhi": ["にぃ"],
				\ "nhu": ["にゅ"],
				\ "nhe": ["にぇ"],
				\ "nho": ["にょ"],
				\ "hna": ["ひゃ"],
				\ "hni": ["ひぃ"],
				\ "hnu": ["ひゅ"],
				\ "hne": ["ひぇ"],
				\ "hno": ["ひょ"],
				\ "mva": ["みゃ"],
				\ "mvi": ["みぃ"],
				\ "mvu": ["みゅ"],
				\ "mve": ["みぇ"],
				\ "mvo": ["みょ"],
				\ "rga": ["りゃ"],
				\ "rgi": ["りぃ"],
				\ "rgu": ["りゅ"],
				\ "rge": ["りぇ"],
				\ "rgo": ["りょ"],
				\ "gra": ["ぎゃ"],
				\ "gri": ["ぎぃ"],
				\ "gru": ["ぎゅ"],
				\ "gre": ["ぎぇ"],
				\ "gro": ["ぎょ"],
				\ "zma": ["じゃ"],
				\ "zmi": ["じぃ"],
				\ "zmu": ["じゅ"],
				\ "zme": ["じぇ"],
				\ "zmo": ["じょ"],
				\ "dna": ["ぢゃ"],
				\ "dni": ["ぢぃ"],
				\ "dnu": ["ぢゅ"],
				\ "dne": ["ぢぇ"],
				\ "dno": ["ぢょ"],
				\ "bva": ["びゃ"],
				\ "bvi": ["びぃ"],
				\ "bvu": ["びゅ"],
				\ "bve": ["びぇ"],
				\ "bvo": ["びょ"],
				\ "pna": ["ぴゃ"],
				\ "pni": ["ぴぃ"],
				\ "pnu": ["ぴゅ"],
				\ "pne": ["ぴぇ"],
				\ "pno": ["ぴょ"],
			\ })
			call skkeleton#register_kanatable('rom', {
				\ "fa": ["ふぁ"],
				\ "fi": ["ふぃ"],
				\ "fu": ["ふ"],
				\ "fe": ["ふぇ"],
				\ "fo": ["ふぉ"],
				\ "va": ["う゛ぁ"],
				\ "vi": ["う゛ぃ"],
				\ "vu": ["う゛"],
				\ "ve": ["う゛ぇ"],
				\ "vo": ["う゛ぉ"],
			   \ })
			call skkeleton#register_kanatable('rom', {
				\ "twa": ["てゃ"],
				\ "twi": ["てぃ"],
				\ "twu": ["てゅ"],
				\ "twe": ["てぇ"],
				\ "two": ["てょ"],
				\ "dba": ["でゃ"],
				\ "dbi": ["でぃ"],
				\ "dbu": ["でゅ"],
				\ "dbe": ["でぇ"],
				\ "dbo": ["でょ"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "wma": ["うぁ"],
				\ "wmi": ["うぃ"],
				\ "wmu": ["うぅ"],
				\ "wme": ["うぇ"],
				\ "wmo": ["うぉ"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ ";" : ["っ"],
				\ "`a": ["ぁ"],
				\ "`i": ["ぃ"],
				\ "`u": ["ぅ"],
				\ "`e": ["ぇ"],
				\ "`o": ["ぉ"],
				\ "`wa": ["ゎ"],
				\ "`we": ["ゑ"],
				\ "`wi": ["ゐ"],
				\ "`ya": ["ゃ"],
				\ "`yu": ["ゅ"],
				\ "`yo": ["ょ"],
				\ "`ys": ["ゃ"],
				\ "`yh": ["ゅ"],
				\ "`yn": ["ょ"],
				\ "`d": ["←"],
				\ "`n": ["→"],
				\ "`t": ["↑"],
				\ "`h": ["↓"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "'": ["あん"],
				\ "x": ["いん"],
				\ "k": ["うん"],
				\ "j": ["えん"],
				\ "q": ["おん"],
				\ "c'": ["かん"],
				\ "cx": ["きん"],
				\ "ck": ["くん"],
				\ "cj": ["けん"],
				\ "cq": ["こん"],
				\ "s'": ["さん"],
				\ "sx": ["しん"],
				\ "sk": ["すん"],
				\ "sj": ["せん"],
				\ "sq": ["そん"],
				\ "t'": ["たん"],
				\ "tx": ["ちん"],
				\ "tk": ["つん"],
				\ "tj": ["てん"],
				\ "tq": ["とん"],
				\ "n'": ["なん"],
				\ "nx": ["にん"],
				\ "nk": ["ぬん"],
				\ "nj": ["ねん"],
				\ "nq": ["のん"],
				\ "h'": ["はん"],
				\ "hx": ["ひん"],
				\ "hk": ["ふん"],
				\ "hj": ["へん"],
				\ "hq": ["ほん"],
				\ "m'": ["まん"],
				\ "mx": ["みん"],
				\ "mk": ["むん"],
				\ "mj": ["めん"],
				\ "mq": ["もん"],
				\ "y'": ["やん"],
				\ "yk": ["ゆん"],
				\ "yq": ["よん"],
				\ "r'": ["らん"],
				\ "rx": ["りん"],
				\ "rk": ["るん"],
				\ "rj": ["れん"],
				\ "rq": ["ろん"],
				\ "w'": ["わん"],
				\ "wx": ["うぃん"],
				\ "wk": ["うん"],
				\ "wj": ["うぇん"],
				\ "wq": ["うぉん"],
				\ "g'": ["がん"],
				\ "gx": ["ぎん"],
				\ "gk": ["ぐん"],
				\ "gj": ["げん"],
				\ "gq": ["ごん"],
				\ "z'": ["ざん"],
				\ "zx": ["じん"],
				\ "zk": ["ずん"],
				\ "zj": ["ぜん"],
				\ "zq": ["ぞん"],
				\ "d'": ["だん"],
				\ "dx": ["ぢん"],
				\ "dk": ["づん"],
				\ "dj": ["でん"],
				\ "dq": ["どん"],
				\ "b'": ["ばん"],
				\ "bx": ["びん"],
				\ "bk": ["ぶん"],
				\ "bj": ["べん"],
				\ "bq": ["ぼん"],
				\ "p'": ["ぱん"],
				\ "px": ["ぴん"],
				\ "pk": ["ぷん"],
				\ "pj": ["ぺん"],
				\ "pq": ["ぽん"],
				\ "cg'": ["きゃん"],
				\ "cgx": ["きぃん"],
				\ "cgk": ["きゅん"],
				\ "cgj": ["きぇん"],
				\ "cgq": ["きょん"],
				\ "sh'": ["しゃん"],
				\ "shx": ["しぃん"],
				\ "shk": ["しゅん"],
				\ "shj": ["しぇん"],
				\ "shq": ["しょん"],
				\ "th'": ["ちゃん"],
				\ "thx": ["ちぃん"],
				\ "thk": ["ちゅん"],
				\ "thj": ["ちぇん"],
				\ "thq": ["ちょん"],
				\ "nh'": ["にゃん"],
				\ "nhx": ["にぃん"],
				\ "nhk": ["にゅん"],
				\ "nhj": ["にぇん"],
				\ "nhq": ["にょん"],
				\ "hn'": ["ひゃん"],
				\ "hnx": ["ひぃん"],
				\ "hnk": ["ひゅん"],
				\ "hnj": ["ひぇん"],
				\ "hnq": ["ひょん"],
				\ "mv'": ["みゃん"],
				\ "mvx": ["みぃん"],
				\ "mvk": ["みゅん"],
				\ "mvj": ["みぇん"],
				\ "mvq": ["みょん"],
				\ "rg'": ["りゃん"],
				\ "rgx": ["りぃん"],
				\ "rgk": ["りゅん"],
				\ "rgj": ["りぇん"],
				\ "rgq": ["りょん"],
				\ "gr'": ["ぎゃん"],
				\ "grx": ["ぎぃん"],
				\ "grk": ["ぎゅん"],
				\ "grj": ["ぎぇん"],
				\ "grq": ["ぎょん"],
				\ "zm'": ["じゃん"],
				\ "zmx": ["じぃん"],
				\ "zmk": ["じゅん"],
				\ "zmj": ["じぇん"],
				\ "zmq": ["じょん"],
				\ "dn'": ["ぢゃん"],
				\ "dnx": ["ぢぃん"],
				\ "dnk": ["ぢゅん"],
				\ "dnj": ["ぢぇん"],
				\ "dnq": ["ぢょん"],
				\ "bv'": ["びゃん"],
				\ "bvx": ["びぃん"],
				\ "bvk": ["びゅん"],
				\ "bvj": ["びぇん"],
				\ "bvq": ["びょん"],
				\ "pn'": ["ぴゃん"],
				\ "pnx": ["ぴぃん"],
				\ "pnk": ["ぴゅん"],
				\ "pnj": ["ぴぇん"],
				\ "pnq": ["ぴょん"],
				\ "f'": ["ふぁん"],
				\ "fx": ["ふぃん"],
				\ "fk": ["ふん"],
				\ "fj": ["ふぇん"],
				\ "fq": ["ふぉん"],
				\ "v'": ["う゛ぁん"],
				\ "vx": ["う゛ぃん"],
				\ "vk": ["う゛ん"],
				\ "vj": ["う゛ぇん"],
				\ "vq": ["う゛ぉん"],
				\ "tw'": ["てゃん"],
				\ "twx": ["てぃん"],
				\ "twk": ["てゅん"],
				\ "twj": ["てぇん"],
				\ "twq": ["てょん"],
				\ "db'": ["でゃん"],
				\ "dbx": ["でぃん"],
				\ "dbk": ["でゅん"],
				\ "dbj": ["でぇん"],
				\ "dbq": ["でょん"],
				\ "wm'": ["うぁん"],
				\ "wmx": ["うぃん"],
				\ "wmk": ["うぅん"],
				\ "wmj": ["うぇん"],
				\ "wmq": ["うぉん"],
			\ })
			call skkeleton#register_kanatable('rom', {
				\ "c;": ["かい"],
				\ "c,": ["こう"],
				\ "c.": ["けい"],
				\ "cp": ["くう"],
				\ "cy": ["くい"],
				\ "s;": ["さい"],
				\ "s,": ["そう"],
				\ "s.": ["せい"],
				\ "sp": ["すう"],
				\ "sy": ["すい"],
				\ "t;": ["たい"],
				\ "t,": ["とう"],
				\ "t.": ["てい"],
				\ "tp": ["つう"],
				\ "ty": ["つい"],
				\ "n;": ["ない"],
				\ "n,": ["のう"],
				\ "n.": ["ねい"],
				\ "np": ["ぬう"],
				\ "ny": ["ぬい"],
				\ "h;": ["はい"],
				\ "h,": ["ほう"],
				\ "h.": ["へい"],
				\ "hp": ["ふう"],
				\ "hy": ["ふい"],
				\ "m;": ["まい"],
				\ "m,": ["もう"],
				\ "m.": ["めい"],
				\ "mp": ["むう"],
				\ "my": ["むい"],
				\ "y;": ["やい"],
				\ "y,": ["よう"],
				\ "y.": ["いう"],
				\ "yp": ["ゆう"],
				\ "yy": ["ゆい"],
				\ "r;": ["らい"],
				\ "r,": ["ろう"],
				\ "r.": ["れい"],
				\ "rp": ["るう"],
				\ "ry": ["るい"],
				\ "w;": ["わい"],
				\ "w,": ["うぉー"],
				\ "w.": ["うぇい"],
				\ "wp": ["うぅ"],
				\ "wy": ["うい"],
				\ "g;": ["がい"],
				\ "g,": ["ごう"],
				\ "g.": ["げい"],
				\ "gp": ["ぐう"],
				\ "gy": ["ぐい"],
				\ "z;": ["ざい"],
				\ "z,": ["ぞう"],
				\ "z.": ["ぜい"],
				\ "zp": ["ずう"],
				\ "zy": ["ずい"],
				\ "d;": ["だい"],
				\ "d,": ["どう"],
				\ "d.": ["でい"],
				\ "dp": ["づう"],
				\ "dy": ["づい"],
				\ "b;": ["ばい"],
				\ "b,": ["ぼう"],
				\ "b.": ["べい"],
				\ "bp": ["ぶう"],
				\ "by": ["ぶい"],
				\ "p;": ["ぱい"],
				\ "p,": ["ぽう"],
				\ "p.": ["ぺい"],
				\ "pp": ["ぷう"],
				\ "py": ["ぷい"],
				\ "cg;": ["きゃい"],
				\ "cg,": ["きょう"],
				\ "cg.": ["きぇい"],
				\ "cgp": ["きゅう"],
				\ "cgy": ["きゅい"],
				\ "sh;": ["しゃい"],
				\ "sh,": ["しょう"],
				\ "sh.": ["しぇい"],
				\ "shp": ["しゅう"],
				\ "shy": ["しゅい"],
				\ "th;": ["ちゃい"],
				\ "th,": ["ちょう"],
				\ "th.": ["ちぇい"],
				\ "thp": ["ちゅう"],
				\ "thy": ["ちゅい"],
				\ "nh;": ["にゃい"],
				\ "nh,": ["にょう"],
				\ "nh.": ["にぇい"],
				\ "nhp": ["にゅう"],
				\ "nhy": ["にゅい"],
				\ "hn;": ["ひゃい"],
				\ "hn,": ["ひょう"],
				\ "hn.": ["ひぇい"],
				\ "hnp": ["ひゅう"],
				\ "hny": ["ひゅい"],
				\ "mv;": ["みゃい"],
				\ "mv,": ["みょう"],
				\ "mv.": ["みぇい"],
				\ "mvp": ["みゅう"],
				\ "mvy": ["みゅい"],
				\ "rg;": ["りゃい"],
				\ "rg,": ["りょう"],
				\ "rg.": ["りぇい"],
				\ "rgp": ["りゅう"],
				\ "rgy": ["りゅい"],
				\ "gr;": ["ぎゃい"],
				\ "gr,": ["ぎょう"],
				\ "gr.": ["ぎぇい"],
				\ "grp": ["ぎゅう"],
				\ "gry": ["ぎゅい"],
				\ "zm;": ["じゃい"],
				\ "zm,": ["じょう"],
				\ "zm.": ["じぇい"],
				\ "zmp": ["じゅう"],
				\ "zmy": ["じゅい"],
				\ "dn;": ["ぢゃい"],
				\ "dn,": ["ぢょう"],
				\ "dn.": ["ぢぇい"],
				\ "dnp": ["ぢゅう"],
				\ "dny": ["ぢゅい"],
				\ "bv;": ["びゃい"],
				\ "bv,": ["びょう"],
				\ "bv.": ["びぇい"],
				\ "bvp": ["びゅう"],
				\ "bvy": ["びゅい"],
				\ "pn;": ["ぴゃい"],
				\ "pn,": ["ぴょう"],
				\ "pn.": ["ぴぇい"],
				\ "pnp": ["ぴゅう"],
				\ "pny": ["ぴゅい"],
				\ "f;": ["ふぁい"],
				\ "f,": ["ふぉー"],
				\ "f.": ["ふぇい"],
				\ "fp": ["ふう"],
				\ "fy": ["ふい"],
				\ "v;": ["う゛ぁい"],
				\ "v,": ["う゛ぉー"],
				\ "v.": ["う゛ぇい"],
				\ "vp": ["う゛ー"],
				\ "vy": ["う゛い"],
				\ "tw;": ["てゃい"],
				\ "tw,": ["てょう"],
				\ "tw.": ["てぇい"],
				\ "twp": ["てゅう"],
				\ "twy": ["てゅい"],
				\ "db;": ["でゃい"],
				\ "db,": ["でょう"],
				\ "db.": ["でぇい"],
				\ "dbp": ["でゅう"],
				\ "dby": ["でゅい"],
				\ "wm;": ["うぁい"],
				\ "wm,": ["うぉう"],
				\ "wm.": ["うぇい"],
				\ "wmp": ["うぅう"],
				\ "wmy": ["うい"],
			\ })
			call skkeleton#register_kanatable('rom', {
				\ "yg": ["ゆう"],
				\ "yh": ["ゆ"],
				\ "ym": ["ゆん"],
				\ "yv": ["よん"],
				\ "yz": ["やん"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "ps": ["ぱ"],
				\ "pd": ["ぴ"],
				\ "ph": ["ぷ"],
				\ "pt": ["ぺ"],
				\ "pz": ["ぽん"],
				\ "pb": ["ぴん"],
				\ "pm": ["ぷん"],
				\ "pw": ["ぺん"],
				\ "pv": ["ぱん"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "pc": ["ぴゅう"],
				\ "pl": ["ぴょう"],
				\ "fc": ["ふゅー"],
				\ "fl": ["ふぉー"],
				\ "gc": ["ぎゅう"],
				\ "gl": ["ぎょう"],
				\ "cc": ["きゅう"],
				\ "cl": ["きょう"],
				\ "rc": ["りゅう"],
				\ "rl": ["りょう"],
				\ "ht": ["ひゅう"],
				\ "hs": ["ひょう"],
				\ "tt": ["ちゅう"],
				\ "ts": ["ちょう"],
				\ "nt": ["にゅう"],
				\ "ns": ["にょう"],
				\ "st": ["しゅう"],
				\ "ss": ["しょう"],
				\ "bw": ["びゅう"],
				\ "bz": ["びょう"],
				\ "mw": ["みゅう"],
				\ "mz": ["みょう"],
				\ "wz": ["ウォー"],
				\ "vw": ["ウ゛ュー"],
				\ "vz": ["ウ゛ォー"],
				\ "zw": ["じゅう"],
				\ "zz": ["じょう"],
				\})
			call skkeleton#register_kanatable('rom', {
				\ "grr": ["ぎょく"],
				\ "grl": ["ぎゃく"],
				\ "cgr": ["きょく"],
				\ "cgl": ["きゃく"],
				\ "rgr": ["りょく"],
				\ "rgl": ["りゃく"],
				\ "hns": ["ひゃく"],
				\ "thn": ["ちょく"],
				\ "ths": ["ちゃく"],
				\ "nhn": ["にょく"],
				\ "nhs": ["にゃく"],
				\ "shn": ["しょく"],
				\ "shs": ["しゃく"],
				\ "sht": ["しゅつ"],
				\ "pns": ["ぴゃく"],
				\ "bvv": ["びょく"],
				\ "bvz": ["びゃく"],
				\ "mvv": ["みょく"],
				\ "mvz": ["みゃく"],
				\ "zvv": ["じょく"],
				\ "zvz": ["じゃく"],
				\ "zmw": ["じゅく"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "yg": ["より"],
				\ "yc": ["いう"],
				\ "yr": ["よる"],
				\ "yl": ["やる"],
				\ "yd": ["よい"],
				\ "yt": ["よって"],
				\ "yn": ["よく"],
				\ "ys": ["やく"],
				\ "yb": ["ゆび"],
				\ "yw": ["いわれ"],
				\ })
			call skkeleton#register_kanatable('rom', {
				\ "ff": ["ふり"],
				\ "fg": ["ふる"],
				\ "fn": ["ふぁん"],
				\ "fm": ["ふむ"],
				\ "gt": ["ごと"],
				\ "gn": ["ごく"],
				\ "gs": ["がく"],
				\ "cr": ["から"],
				\ "cd": ["かた"],
				\ "ct": ["こと"],
				\ "cb": ["かんがえ"],
				\ "cn": ["こく"],
				\ "cs": ["かく"],
				\ "rr": ["られ"],
				\ "rn": ["らん"],
				\ "dg": ["だが"],
				\ "dc": ["でき"],
				\ "dr": ["である"],
				\ "dl": ["でしょう"],
				\ "dd": ["ので"],
				\ "dt": ["だち"],
				\ "ds": ["です"],
				\ "dm": ["でも"],
				\ "sf": ["さり"],
				\ "sg": ["され"],
				\ "sc": ["した"],
				\ "snt": ["しなくて"],
				\ "snw": ["しなくては"],
				\ "snm": ["しなくても"],
				\ "snb": ["しなければ"],
				\ "sr": ["する"],
				\ "sm": ["しも"],
				\ "sz": ["それぞれ"],
				\ "tc": ["ついて"],
				\ "td": ["という"],
				\ "tl": ["とく"],
				\ "tr": ["ところ"],
				\ "tg": ["として"],
				\ "tf": ["とり"],
				\ "tn": ["との"],
				\ "tb": ["たび"],
				\ "tm": ["ため"],
				\ "tv": ["とき"],
				\ "tz": ["てき"],
				\ "nf": ["なり"],
				\ "nr": ["なる"],
				\ "nl": ["なった"],
				\ "nw": ["なくては"],
				\ "nm": ["なくても"],
				\ "nb": ["なければ"],
				\ "nd": ["など"],
				\ "nc": ["について"],
				\ "nz": ["なく"],
				\ "hg": ["ふる"],
				\ "hc": ["ひゅう"],
				\ "hl": ["ひょう"],
				\ "hd": ["ほど"],
				\ "hh": ["ひと"],
				\ "hz": ["ひじょう"],
				\ "hr": ["ひとり"],
				\ "br": ["ばら"],
				\ "bh": ["ぶつ"],
				\ "bt": ["べつ"],
				\ "mr": ["まる"],
				\ "md": ["まで"],
				\ "mt": ["また"],
				\ "mn": ["もの"],
				\ "ms": ["ます"],
				\ "mm": ["おも"],
				\ "wr": ["われ"],
				\ "wt": ["わたし"],
				\ "wn": ["われわれ"],
				\ "vm": ["ことな"],
				\ "vv": ["おなじ"],
				\ "zr": ["ざる"],
				\ "zt": ["ずつ"],
				\ "zn": ["ぞく"],
				\ "zs": ["ざく"],
				\ "pf": ["ぷり"],
				\ "pg": ["ぷる"],
				\ "pr": ["ぷろ"],
				\ })
			]])
		end
	},
	{
		"delphinus/skkeleton_indicator.nvim",
		branch = "main",
		opts = {}
	},
	{
		name = "nvim-treesitter",
		dir = "@nvim_treesitter@",
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter").setup({
				ensure_installed = { "c", "lua", "vim", "vimdoc", "query", "javascript", "html", "markdown" },
				sync_install = false,
				highlight = { enable = true },
				indent = { enable = true },
			})
		end
	},

	{
		-- 自動でフォーマットするためだけに入れているが他に良い方法があるかも
		name = "conform-nvim",
		dir = "@conform_nvim@",
		opts = {
			format_on_save = {
				timeout = 500,
				lsp_fallback = true,
			},
		},
	},
	{
		-- 何故か Python はこれがないとformat できない。
		name = "null-ls.nvim",
		dir = "@null_ls_nvim@",
		config = function()
			local null_ls = require("null-ls")
			null_ls.setup({
				sources = {
					null_ls.builtins.formatting.black,
					null_ls.builtins.formatting.isort,
					null_ls.builtins.formatting.nixfmt,
				},
			})
		end,
	},
	{
		"epwalsh/obsidian.nvim",
		opts   = {
			workspaces = {
				{
					name = "obsidian",
					path = "~/obsidian",
				},
			},
		},
		ft     = { "markdown" },
		config = function()
			vim.g.conceallevel = 2
		end
	},
	{
		name = "rust-tools.nvim",
		dir = "@rust_tools_nvim@",
		ft = { "rust" },
	},
	{
		name = "lualie.nvim",
		dir = "@lualine_nvim@",
		dependencies = { {
			name = "nvim-web-devicons",
			dir = "@nvim_web_devicons@",
		} }
	},
	{
		name = "toggleterm.nvim",
		dir = "@toggleterm_nvim@",
		opts = {
			direction = "float",
			float_opts = {
				border = "curved",
				winblend = 30,
			},
		},
	},
	{
		name = "tokyonight.nvim",
		dir = "@tokyonight_nvim@",
		lazy = false,
		priority = 1000,
		opts = {
			style = "storm",
		},
	},
	{
		name = "telescope.nvim",
		dir = "@telescope_nvim@",
		dependencies = {
			{
				name = "plenary.nvim",
				dir = "@plenary_nvim@",
			},
		},
		config = function()
			require('telescope').load_extension "file_browser"
		end
	},
	{
		name = "telescope-file-browser.nvim",
		dir = "@telescope_file_browser_nvim@",
	},
	{
		name = "noice.nvim",
		dir = "@noice_nvim@",
		opts = {
			cmdline = {
				enabled = true,
			},
		},
		dependencies = {
			{
				name = "nui.nvim",
				dir = "@nui_nvim@",
			},
		},
	},
	{
		name = "copilot.vim",
		dir = "@copilot_vim@",
	},
	{
		name = "nvim-lspconfig",
		dir = "@nvim_lspconfig@",
	},
	{
		name = "nvim-cmp",
		dir = "@nvim_cmp@",
		dependencies = {
			{
				name = "cmp-path",
				dir = "@cmp_path@",
			},
			{
				name = "luasnip",
				dir = "@luasnip@",
			},
			{
				name = "cmp-nvim-lsp",
				dir = "@cmp_nvim_lsp@",
			},
			{
				name = "cmp-buffer",
				dir = "@cmp_buffer@",
			},
			{
				'rinx/cmp-skkeleton',
			},
		},
	},
}
