{
  imports = [
    ./direnv.nix
    ./github.nix
    ./lazygit/lazygit.nix
    ./alacritty.nix
    ./fzf.nix
    ./git.nix
    ./neovim/neovim.nix
    ./tmux.nix
    ./nushell
    ./zsh
    ./zoxide.nix
    ./bat.nix
    ./packages.nix
    ./fd.nix
    ./ripgrep.nix
    ./eza.nix
    ./wezterm/wezterm.nix
    ./fish.nix
    ./starship.nix
  ];
}
