token: ENC[AES256_GCM,data:7Z0M9yZ0SPa9C7xXaGljA+QmQ1+5ifi7VjFlz7val078TPuGIA4mug==,iv:Ev35gEd6y0bE5rnK5jfTLnjVVulzwDalwJ0LobUErKo=,tag:5+J5QYproMlfK5q0CZNCaQ==,type:str]
sops:
  shamir_threshold: 1
  age:
    - recipient: age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTW5pYkwwTWd5eEhTclpI
        OVFWTDdFMkZTaGVCVTRobTZxSW9qY1h6SjBNCkhHcTJxdUdiMXkrWTNQcGF4UWpm
        Zzc5Q1pSNGNtMjhZdG80cXBRUFR0V1UKLS0tIGo3aG5iS0VwV3NaQU9mclNscHVn
        TFFvS3dmUFluRDBYbUVmNHE5ZFZFaGsKk3vwCH1ekL2Nk1kAng/4wb0g3y4Ywd9U
        ZZhx9fvUSvx6rcxpUzOpxj6szR6aaJFhEBQN0XU3nHiuXBNKA5XsfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T09:10:10Z"
  mac: ENC[AES256_GCM,data:hPM0UwTuiq+0A5o7DPPWMB2WnAVVR230+OjE2XgjZaHTsHN/A3EPQ2j1m8tiXl+UZMwPyy3wjmAinmp4f1zPhO8CgFNd5ebsf9SmZ5jQWhVvXH07/SAw0+WbDErXbG86wz6mQgE1qS9k4t4IFC/d5GqlCDdbtWUsklpfH/cAuN0=,iv:MwEMh5IFTg6GzqQI817nrWeQl0i4fcA/ZSHjkNu+seI=,tag:qcFd1yrpTT0E5tH1AN5+AQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
