"Environment
set undodir=$XDG_CACHE_HOME/vim/undo
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"