name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
    - name: Setup cachix
      uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: yus314
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
