gh-token: ENC[AES256_GCM,data:hU/8JNcs8Dyd2nXUflDGLOv1kQ8GDKrXLqi+KMy2jMmx07MIY25mww==,iv:mReaeUJOwY94ayKHsBApwazhlWTYr2mIfW9mis+J3cU=,tag:ZONzsLvTUo7ThEoRWN+PSQ==,type:str]
dropbox:
    token:
        access_token: ENC[AES256_GCM,data:yOc5EGDvysJjNS2HWhtQC2+xB/ryiybKD1K0HM7uHALiGr9A53aLkE1IYnIfad7HfVVekpwCGkLrY9WRaD7IFdukmnJdFuRMY3Ft8wJHBXAYHoMm23tQm5DJEB56JtXVi93wJVDXErwK0PPnjkdlAAkPwJkShsa4+X1uVowcrG7b/hRK7i5j6XvgaCsq48Plaf4=,iv:owWmg0EOu1lopUS5GklCPYD+Sj9kuoQ8fjKp03ARMRM=,tag:bTaTdsLJyowYaEKcXFO1Lg==,type:str]
        token_type: ENC[AES256_GCM,data:qdoUvsT9,iv:LvQLFWkT8c9EgE89Bp7kwte1G0KmWJSHIZwDT6Jc/lI=,tag:gJy4PfP6iKMaTGqxRDHu4Q==,type:str]
        refresh_token: ENC[AES256_GCM,data:DtePCSNtVhVJBvLyfndyKZhd0e2heL9Fp5UhMn1q41Q53yUZxlZg9nP0Vjk+2P7LIfpzsouvR/MTV2mKeIPoFQ==,iv:rpx6EUUnRnk8KrQWyxzV4+nQ1LVXg0IYW4mQ7ZSOeaE=,tag:PkRSNtCKYgCjetHIUUl9lQ==,type:str]
        expiry: ENC[AES256_GCM,data:GUEmxd9+Jwjp6cwoRcC+NgyR39ZSQ8C3IZkTPlw7myIYsI8=,iv:ooIzpQt74dMY+NJFEQK23uzeak1dkrmo/7JmSi5VUz8=,tag:jRovyT9Ti9ZuqgleTmkdWg==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - pgp:
            - created_at: "2025-05-20T02:52:46Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA/9/hScqd0Z7ARAAiljlreIQoLcOICyPYJ7Y3YzTzWlDxDFTPLGYG2A9a6Zh
                YMfFtLeLUfjR5p24Y4DacWj+AFQ0FELBQJtxxHYVGrwdIXVzGoIR0WnCA1yGUDlS
                Ocw/ocCxeWD3Uoo56AjEFwaNlxBfXo2lroGdpwVK17kU3krZESPE28JRxBf3Qsfj
                M+t9i90S1TUGHPYEgJ1VhRYqsj9VHMNIOZXIwgVkSYQ+MDlih7yPWOFk2Tyj4fZQ
                ZtAsIUHwGps3GXUN+eGjmJ01T5oqqtQpdwlzPQG0PNGJ0Y3eoatCgM7WfgPlDsRj
                DPbgClOpXtEb1PUoWCUeFVacVeqGk+lNui+fL/GgJ+pqeVe+oGBWvUG8xk88J3bH
                7b+weejkbR3O3+4TIXbY3RtqOW+zr2/IcQhuDQ9E0HKwMTnziB5BiinQnd2HtB5Y
                uUrt043k2/LC05VEzOMQtgIqwq1ZYPTOXHP2jGRaeQlA3gsFVSKcCUHdSAhDs/6d
                Z23gNvucylgIVNFtIKbZ2zlV9/YiuYTMtLGyo3O+1+jWTgkqQmOpKUz7UINQE44s
                G/Om4Vi5NjBNHFAnxHQXbLJSdhuMbqwIEsfhty5mr/9MQXF0lQDSlFS1uwFyahT0
                ZwJD57/1H2jHsQlJRixTWF7hhJOpvVIgz9h0f6vBfJsk7Hasynq0rA1AE8tTF2PS
                XwHvlpMznd5lXhURyI6DeN0s6TqqwGyMnBbpHaVEIChx+3aNpEkmX0rsmsbwckFS
                O9hRYMzQHE8bY4MaF11Sh6WFCIlky3B1Hkvy323CTlezDTbc40e9+EpLVbQCC/pw
                =h8Vk
                -----END PGP MESSAGE-----
              fp: D1070BA2EC9EFAFECDA9389101EC441050EDC406
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaktoOXo4ckpHYmF4ZkJE
                TTRhNmgxVlRLNlR6UG0wWkR4QXhyTEFEWHhvCkxZbFFwc0ZRSmFtcnE1OVpSbVlT
                cXNjUzdZQlh1YVM5eExWS0VXT25aYzAKLS0tIGlENittRTgzRFJ5bzdKY3NEM044
                Qm0rTExiMmhtNzdBczFxVHZ6d0ErNUUKd5oF75Af5H/HUyt2RYh0T5yzBUlzTDvl
                uXiZXEocgLSdw+JIGsm595p1INMViUR1NvQUfRTe8DOnC1adUGNMjw4=
                -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T16:22:29Z"
    mac: ENC[AES256_GCM,data:YxWSC511d0AglUVQ3aS/AySWSpkxWNgtbZlqwKiBuNubdXCsiCO0r8c7/qd8DWXe/eGKkgP7IlQmIW86mcpjAXxJti7hPUXCuIWSSE+2ByBXZqXd8pvKeZhMVZEQ/LUgtS/K3oI+6O6wo9qXpVjrsxdeAUfeLaoANaje0a7fifs=,iv:5+P5hnUPzvXvmxtALs1Dlh7cmMDs3cTTV5IuhHeNS3g=,tag:YQyCvsjXiPZkFSOay1I/gA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
