gh-token: ENC[AES256_GCM,data:hU/8JNcs8Dyd2nXUflDGLOv1kQ8GDKrXLqi+KMy2jMmx07MIY25mww==,iv:mReaeUJOwY94ayKHsBApwazhlWTYr2mIfW9mis+J3cU=,tag:ZONzsLvTUo7ThEoRWN+PSQ==,type:str]
dropbox:
    token:
        access_token: ENC[AES256_GCM,data:yOc5EGDvysJjNS2HWhtQC2+xB/ryiybKD1K0HM7uHALiGr9A53aLkE1IYnIfad7HfVVekpwCGkLrY9WRaD7IFdukmnJdFuRMY3Ft8wJHBXAYHoMm23tQm5DJEB56JtXVi93wJVDXErwK0PPnjkdlAAkPwJkShsa4+X1uVowcrG7b/hRK7i5j6XvgaCsq48Plaf4=,iv:owWmg0EOu1lopUS5GklCPYD+Sj9kuoQ8fjKp03ARMRM=,tag:bTaTdsLJyowYaEKcXFO1Lg==,type:str]
        token_type: ENC[AES256_GCM,data:qdoUvsT9,iv:LvQLFWkT8c9EgE89Bp7kwte1G0KmWJSHIZwDT6Jc/lI=,tag:gJy4PfP6iKMaTGqxRDHu4Q==,type:str]
        refresh_token: ENC[AES256_GCM,data:DtePCSNtVhVJBvLyfndyKZhd0e2heL9Fp5UhMn1q41Q53yUZxlZg9nP0Vjk+2P7LIfpzsouvR/MTV2mKeIPoFQ==,iv:rpx6EUUnRnk8KrQWyxzV4+nQ1LVXg0IYW4mQ7ZSOeaE=,tag:PkRSNtCKYgCjetHIUUl9lQ==,type:str]
        expiry: ENC[AES256_GCM,data:GUEmxd9+Jwjp6cwoRcC+NgyR39ZSQ8C3IZkTPlw7myIYsI8=,iv:ooIzpQt74dMY+NJFEQK23uzeak1dkrmo/7JmSi5VUz8=,tag:jRovyT9Ti9ZuqgleTmkdWg==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZElLUjRIcnFaUDl4Q1hC
            WlBORXM2cG5FTkRhbTg2VmJBYUtkbGd0VFNzClcvcWZMZ0FKWEJNOHZ6VzlhQkF5
            VDFvNG0raEV0cEkzUDNpbGNtOGo0bjQKLS0tIG5hSjNTQ0dnNjA2MXkycjlxSnVz
            Y1JLY0V0SXo1MkpBZjl1S1NnbXVkYzgK+8nY7wu66daWimoaemYDpU4/u+voimB/
            qkR0bR7clawKDBd7uHRceeKox0zRTkUFMbD8D8xgmI445pygyWdXKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T16:22:29Z"
    mac: ENC[AES256_GCM,data:YxWSC511d0AglUVQ3aS/AySWSpkxWNgtbZlqwKiBuNubdXCsiCO0r8c7/qd8DWXe/eGKkgP7IlQmIW86mcpjAXxJti7hPUXCuIWSSE+2ByBXZqXd8pvKeZhMVZEQ/LUgtS/K3oI+6O6wo9qXpVjrsxdeAUfeLaoANaje0a7fifs=,iv:5+P5hnUPzvXvmxtALs1Dlh7cmMDs3cTTV5IuhHeNS3g=,tag:YQyCvsjXiPZkFSOay1I/gA==,type:str]
    pgp:
        - created_at: "2025-05-21T14:15:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/9/hScqd0Z7ARAAufjou+OvlbZL6JELr8iHHpvRJZ5w6UFfNf9OCtEsMLwP
            mY+4QtkIobFX8Rd5MsKeD8EOFye0EBVlm+QaXGvxK7/qEoey0uVRejSMzmredn9U
            NU+eHuCH+GiKzDPJ/nzScz9WSvMg6esfhKHu4ktqGyIcW0Q6sQ+cbDM0XrELQ1Jx
            lyoKQGz/u8xM/FFIIcNTIZr1oKaodwoC0m4z5T/Uf3eU2HFIVHDnMm6WkzM+/Q21
            YB7X7BdKv/mHw5+QEjS4yHanecxDOZDTJZ+VjpcUHZY3LL9joo+5l4DJKk1EQxvd
            mMJra36cOurELK1Jy7bnvDae2LPQMbAjwo8kQW/vP5/i6TaW+GZgZhSuh6B2gbg5
            uxbrHKD/S0rYC/LF5Da/3KlRFmsEIZHbyx8FWoGRz42pGuQl4cw9LTk8yMDItrXV
            x2Fz2BmVjKz6Ucxw+Qs6kOQgM7dF8qgDUAioVcD8uIC6PkUIC78XGk5hVYj6sg92
            2JOTkEabGvNNAlFakwvb5Y+WmwekacH7xJ4E/7bPxtgrYfR2C0HmzuORDEBpC9GH
            1seJRJRLVWYkrg5gA/eNN9TeKAQ33CKv/8FddtOCLcOYa+0NEOvZz7K7zVWLNDbe
            G+IWcC6JfvSGntdukqT4InRBir9UotV/zDfssZ69KEs4UKHF0zHeEfV6xXHfU7PS
            XAGQR3KFczQBO3pAqP08ER+ZVs839TiXtKqwpFjfnNegRl0dtPywa9Zq8ZcEdNJr
            3a797PRDwGkrAEYQaaPvYkzpxQ9sQjwuq7Uz9MniEolT++iAc7Baz2mzmxMV
            =3tBU
            -----END PGP MESSAGE-----
          fp: D1070BA2EC9EFAFECDA9389101EC441050EDC406
    unencrypted_suffix: _unencrypted
    version: 3.10.2
