gh-token: ENC[AES256_GCM,data:LV2HiFgLTZg+0EBNV8HICDd7MoSZ4SOGLEon1tZyGblXQnFfxRbe,iv:6fCWglpQoT6W0sRb2U7H0agZGzceoouym2F7n+M3j7o=,tag:M3Qj98+PdqzwMQ4Aefw+5Q==,type:str]
dropbox:
    token:
        access_token: ENC[AES256_GCM,data:yOc5EGDvysJjNS2HWhtQC2+xB/ryiybKD1K0HM7uHALiGr9A53aLkE1IYnIfad7HfVVekpwCGkLrY9WRaD7IFdukmnJdFuRMY3Ft8wJHBXAYHoMm23tQm5DJEB56JtXVi93wJVDXErwK0PPnjkdlAAkPwJkShsa4+X1uVowcrG7b/hRK7i5j6XvgaCsq48Plaf4=,iv:owWmg0EOu1lopUS5GklCPYD+Sj9kuoQ8fjKp03ARMRM=,tag:bTaTdsLJyowYaEKcXFO1Lg==,type:str]
        token_type: ENC[AES256_GCM,data:qdoUvsT9,iv:LvQLFWkT8c9EgE89Bp7kwte1G0KmWJSHIZwDT6Jc/lI=,tag:gJy4PfP6iKMaTGqxRDHu4Q==,type:str]
        refresh_token: ENC[AES256_GCM,data:DtePCSNtVhVJBvLyfndyKZhd0e2heL9Fp5UhMn1q41Q53yUZxlZg9nP0Vjk+2P7LIfpzsouvR/MTV2mKeIPoFQ==,iv:rpx6EUUnRnk8KrQWyxzV4+nQ1LVXg0IYW4mQ7ZSOeaE=,tag:PkRSNtCKYgCjetHIUUl9lQ==,type:str]
        expiry: ENC[AES256_GCM,data:GUEmxd9+Jwjp6cwoRcC+NgyR39ZSQ8C3IZkTPlw7myIYsI8=,iv:ooIzpQt74dMY+NJFEQK23uzeak1dkrmo/7JmSi5VUz8=,tag:jRovyT9Ti9ZuqgleTmkdWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNVdKOHJUOUxscXpyblNa
            QkduMVVZcHd5N3VOVjNRZFU1VHpvVDJGUDNFCjhLYjczbk5neU5qV251L1V5dFg3
            ZFhNWEh6bFNwNTFISHAzb3AyMDd6bjgKLS0tIDUwUm1MT1hMK2FuREMyRmUxQmd1
            bExOM3hpV2w4eFlxMGJxMkt2Q1lEZncKYk+2udQzRyHM0RNsnUddbrMMAo1mJ4ui
            ylov9S9hS4lZ4Gsmrq+WBjdD0LQdrpSjBiq5bjHdZIVh2Z4GKk/rng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T07:02:09Z"
    mac: ENC[AES256_GCM,data:q9DIVJ6oMMxKqqQx8C0BaO3tzLM0vBrOtUZt1K9hGE2xXh362gc0yPZoMN3Ly2zaigk1PPYcFOZv5xMouqa9gWMk6nys1aPZh3EM7J2OItrlMR2yKULrlNZ4uAG3vPTZrbLhXxkTNOMobd+cZxwNToQv6qH3EdMRSaGYFKaGWUQ=,iv:RdBFaO7PkkUcWxMCWnnbvhV1bF7QE28/P1EyuhMPFxE=,tag:Si6CKoIUNqcko/HZt4f0OQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
