gh-token: ENC[AES256_GCM,data:hU/8JNcs8Dyd2nXUflDGLOv1kQ8GDKrXLqi+KMy2jMmx07MIY25mww==,iv:mReaeUJOwY94ayKHsBApwazhlWTYr2mIfW9mis+J3cU=,tag:ZONzsLvTUo7ThEoRWN+PSQ==,type:str]
dropbox:
    token:
        access_token: ENC[AES256_GCM,data:yOc5EGDvysJjNS2HWhtQC2+xB/ryiybKD1K0HM7uHALiGr9A53aLkE1IYnIfad7HfVVekpwCGkLrY9WRaD7IFdukmnJdFuRMY3Ft8wJHBXAYHoMm23tQm5DJEB56JtXVi93wJVDXErwK0PPnjkdlAAkPwJkShsa4+X1uVowcrG7b/hRK7i5j6XvgaCsq48Plaf4=,iv:owWmg0EOu1lopUS5GklCPYD+Sj9kuoQ8fjKp03ARMRM=,tag:bTaTdsLJyowYaEKcXFO1Lg==,type:str]
        token_type: ENC[AES256_GCM,data:qdoUvsT9,iv:LvQLFWkT8c9EgE89Bp7kwte1G0KmWJSHIZwDT6Jc/lI=,tag:gJy4PfP6iKMaTGqxRDHu4Q==,type:str]
        refresh_token: ENC[AES256_GCM,data:DtePCSNtVhVJBvLyfndyKZhd0e2heL9Fp5UhMn1q41Q53yUZxlZg9nP0Vjk+2P7LIfpzsouvR/MTV2mKeIPoFQ==,iv:rpx6EUUnRnk8KrQWyxzV4+nQ1LVXg0IYW4mQ7ZSOeaE=,tag:PkRSNtCKYgCjetHIUUl9lQ==,type:str]
        expiry: ENC[AES256_GCM,data:GUEmxd9+Jwjp6cwoRcC+NgyR39ZSQ8C3IZkTPlw7myIYsI8=,iv:ooIzpQt74dMY+NJFEQK23uzeak1dkrmo/7JmSi5VUz8=,tag:jRovyT9Ti9ZuqgleTmkdWg==,type:str]
sops:
    age:
        - recipient: age1zr08ellgzkyaudu2lmjtfp7ffgf3l2su8p3lntku9nr5l8n2ysqs5gcnmw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNVdKOHJUOUxscXpyblNa
            QkduMVVZcHd5N3VOVjNRZFU1VHpvVDJGUDNFCjhLYjczbk5neU5qV251L1V5dFg3
            ZFhNWEh6bFNwNTFISHAzb3AyMDd6bjgKLS0tIDUwUm1MT1hMK2FuREMyRmUxQmd1
            bExOM3hpV2w4eFlxMGJxMkt2Q1lEZncKYk+2udQzRyHM0RNsnUddbrMMAo1mJ4ui
            ylov9S9hS4lZ4Gsmrq+WBjdD0LQdrpSjBiq5bjHdZIVh2Z4GKk/rng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-13T10:33:59Z"
    mac: ENC[AES256_GCM,data:8fFS5N74EhK0G93JPBZW3/jrZel7a01wHC/JqOuUhi2Mg6f5D2IYxkf9qJmxitrEkQfFBWzyteDVdD9fulJBfbHrtdPKIPEbEO+2cvYllFQxM/AwJf18nCxI6aiY3k1o6okex7TiB1tTuPGofwFhTP4h8aEb/j91qQC7WUcHPjA=,iv:RlUxmYxWLXF0zqUEDMYEKCC45VO0nRaf0YSTiiqbTvk=,tag:HnQ2/sJt49LIK+jBDjmpcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
